version: "3.1"
services:
  mongodb:
    container_name: mongo-db
    ports:
      - 27017:27017
    image: mongodb
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongodb:27017/

volumes:
  data: {}
#docker network create mongodb_network
networks:
  default:
    name: mongodb_network
