version: "3.8"
services:
  mongodb:
    container_name: mongo-db
    ports:
      - 27017:27017
    image: mongodb
    volumes:
      - data:/data
    environment:
      - MONGODB_INITDB_USER=rootuser
      - MONGODB_INITDB_PASS=rootpass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 9081:9081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  data: {}
#docker network create mongodb_network
networks:
  default:
    name: mongodb_network
